# Generated by Django 4.2.18 on 2025-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_sponsor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Events",
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="dark_logo",
            field=models.URLField(
                default="https://duckduckgo.com/i/742895b2644223c0.jpg"
            ),
        ),
        migrations.AlterField(
            model_name="sponsor",
            name="light_logo",
            field=models.URLField(
                default="https://duckduckgo.com/i/742895b2644223c0.jpg"
            ),
        ),
    ]
