# Generated by Django 4.2.18 on 2025-01-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_conferencetracks_keymilestones_keynotespeakers_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConferenceTracks",
            new_name="ConferenceTrack",
        ),
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
        migrations.RenameModel(
            old_name="KeyMilestones",
            new_name="KeyMilestone",
        ),
        migrations.RenameModel(
            old_name="KeynoteSpeakers",
            new_name="KeynoteSpeaker",
        ),
    ]
