# Generated by Django 4.2.18 on 2025-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_keymilestone_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keymilestone",
            name="date",
            field=models.DurationField(verbose_name="Milestone Date"),
        ),
    ]
